language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - biss_dimov@hotmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: RtMoriRP6IS7siLEK9RxwUSSijkmf6o3xTsCnr/7GEQ/YjEIJSgklDzhkTJfK85XqFBtI349YFPU4yTTgFUzzRB2gOYSe0cBxXKrSIjsE+erUM5iviSAY8ImXVbevCkdAJcsXlALGf5th91ZBRhhPC7/92MIOLJx/VWWGUPyDsDzO/qo4OdtgdsVOoo9ViL3Kbk2digS3Tg7mnZs7IxyXnrBxhOhGoSHHWCdF1okM2tCbx5TTM2M5l4xe+4Ob9caSndbve6Wn6+AWGPDf0b7uAFnrEdL2MEVTQuG7tUQDjqmeuS+5U7So9EKnddRRk3dbum9cGP+XlsONbO1pc4WTqkLiYLsGiotJdLEbsxAe8S8Yx1/+4xhx3zpCYsxg76h1Pke5+XsqcnNX3YRhySXDVTu8EinPdrkbkcAHd/w3NoJTVCi69z4cUbRrQj/wLYshvtj8/kU9T7iEvBjNq90UIYAfyia6Dz2KiZzHnIS47Uii7kizVf76iU/NpQagOT1E0M0duG/VOWc2pq2YK9sqHK2BDIFsEaNO2bGj3PKRTUaJouAwBSUKa9W9FlEEAoWbptHTIpE8SYrTauEc1Mi3zKVTeZbBK2L/LMijPYvoEiDkCTl2M/bs/a1L5an7SH4LSaMD4yXsSVE2JnIFFcTBQ5d51/p6VKEMOu0N2mGR7o=
  - secure: UjlAAIbv1A3RGpV+ptTDk38X7VtG1ZfO1hGJfktnFSIFf7xXwsM0tVKDC911nR4TeOez3SKIuR3Ft1of5JlEqsDcuf2uZ922cyE9KBBacgTHeqSfnSsfPgW93itlNDoZ+XtFVQrH5Ky1PXcHZtoJaiXPWZmAwVU4CwlD07dhOfoBXU19swO+hM0Pq5v/pbgUVQ9VdZEk6uUzjNUZixLiFv+MFzQUhEoW091oDuVcXLA6j3JXdwbifK8W7forsVSm1C90Enn1tAAjv8SnyaaslwKqyEOewXnegMuIWMkvYcd7pz95DBVO8yfah3pQqeOBNC7EI+0igFIb5ojuXzh6Z4pRkFskDPe/ItP2mWqtz/yyazLDd93Ss+3ILrZ5tAouCg448qSHONxXjPOlDX5exPOGEIM6RGjUcLqfISg/EoMs9rfUKAUJPoYKG3c2cf7NTEazr5D0cuISH10rq6THaTgDXbXjYS3BV0kyF81wlg/9chFBs1ztuj/9BHbJOV4aF6yFzLYDpm6LIDcOxhPmc5rH9J4KRQ4Cib4qK1/NbnbJGl0LqPOtxuLat0Fy9Gf1hyHCQYPqxHYDzbbtyttMijuX9YGpB7DW2Vo+1jxJPQc65m7yeKKS/PQG6wPifWitI42scUV44D/+9+OsFZ3Cv2FsW3x8o5yUIalYVdwwhc0=
  - secure: RI05ZeKpQZ129O17DhFvsqxFRC3v8MXaznwGhzH0vlBt1iPsloQp7XjubM74HTNUbW86EN1jRrjhvO7TSsNbtOvv+jka+vgKLWWB8cxp3q3nOapN1y/fxs4z2e66ohf2bfvWSJv0U9u6J6ultAU6tnEOvlVEEmX2RhU5bjMkK3oo9nDuGF5H0ty8/YKW4FQ432ZQ3IuGH/QLDPxMaAuxHh1Q/sH4nN+sXVizO5Rw2bUafwieqv29bdbCNqtm984kxUlYuVOdukvhgbyPyJg7QWIrhhUCSYtj2H7S2ks1w4hCMTAg+KhenuNDwBaTD8KCxkvKmvIkVlWiWf+6icjpBzofO9ce6yu0c5Aaduxw0AdpHf09zmxDw94DnpJpn1yCHywm+K6Rd/xRxp1fmhO0yie2KC4Vtttz7PFqXhqam+nRvniWI5CgmqEurwbaAP1Zi35U+FiotbQn6r5i/3M6TZDPHvdOzzXkT4RrGU4dpcCKxCRD+UA/m+tLOq9zHgQpSwwYkKNvKUud6ngzK/mhtxoadjw1o50943Bl/CUs269Js4HBkKv8NlT0z6VNo0pH19qp8ndsGEn5jlq98t+pys5W1xiSIFkX4tVbIZrxWCFb4T8KchQ5XS2tXj2qNqCCYQKdCcZCNo00/nuegOKJIibFiH14G8Zbp0uZLmfg2PU=
  - secure: YNvFNXRImNM6B5DcqImzIKSeLJ4bf1yVHBYh8PhSzB2p5Ny4NEurq54dRQzBLpF/v14JBH39jZ70dhPpwv0vAwdMtWnhXDBYw0vFoXmPCKyIY/hzrmouzYCZHWxa4+pniDqrEPezFZ16VljTeT2e/+eweLGHJjWAUIV6OaJ5UN3l+qabDyQHaEDIujyhWzGcyL+aEVAf/gv//PSTe1JImrt9qp57HqaYdMOyYRpcjvb7Wunxvqw2z1DVIbEzqVaUTg1jwu6tBIA79lZimnusZrx9Qmk3r/prYTsxRSCGPKq1qB6zw1veolSi6B7J2XnYI2orVsY0ExbCmp4bHjN/mmHG2G481ncfmp3cVpLaZ9ar4GpzjjEtTx96JRmGvOtEVt+HInHejArUd41533A+gTgDITv8m15DN5jRGRhOxyzpvwyHoN9DP2D7/TvsJVbael/KjajrxAXc+rngPZLyg2VT6mw/gJgxc4Bu6SThWpMnfXj7pl8rt0w0Fi8e6TxiAnCKaw3gdnFTMCav2Jpg27xRDd1v6qp61fWu1MRpDXr3KdpIN/DVT2qM5DRTjislAANY2W5MoSjbHKM+UHAzLPSB6h9u+Dm7z8v/5jIq91VTAs2y31CwEhnABUEZDkWzlfiaKUyNo8VqkVQKEpT3YplDuzNPrm1FVZJkniFJtEo=
  - secure: Xq5bGaKkxRjDtgUoLfP+2eNIGthdnoMa7TE9hRz+VoAHkuBf9aeKqMS3blemCGsv6iXeaCHUpTpBUzhR/U/yzxOCtk7pHyZguqeU8Zmno8LNc5hWkyfgg9Ady7QFoNlFL31bdUu5fdo3DIS4DQHq3dwkAh7rK1S9h/VmPLtChSeCUhbgqtUtxTAJLqivlPEI7oXukS8/2i1oSiV0EDCeHtF7mppm62FFYEHzITSDmUc74b4dzjYLsZA4BJsrugxxSccYIXmNQNzY9E0nbzTpBT/Qr4d765I4gxuu7GUIhQKoZeUSYjYgvJid9k0nb6ktAITLNYm8++eopEY7Q0M4gABWLKWlO1gl9pkTUWnVObmSCX7YMCagHrsVlOTAQYJ4WiKzzfH6/xYO569Azv445I5qrZcJmYQEThMj4X5xSWyOEVTrmVID+hT0K0A0RXWR/K5OSrZR9zne4W6zVWAFSOvsBtZoxNuoyxuRzo/1Q0nvtrDqhdOJ6wuiOc64im2/YJODwB2meZ8VwLJlpyKHkw9QTttElKXckClsLY7h1t///BJ7TY9s52ryhHB7cEOHxk5uvOuDE1Nn/AUikdwUWjNAxQDZRNrqslvkbC6UMYVUs9L1JeTd1oBFmhwN54yQjVRUtX87ZfyTrgGH3Ek28iKNeRpIHJf9piT03eSHsQ4=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=18.191.95.13
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
