language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - biss_dimov@hotmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: CumZvIgzCHvzdqxmG9J5qYU7WrtxcSb7j2tlPkwHfW2lbK+GhxSGF9vxwY04QYKHTdjtlSE7639CDNCyYXCB8vMGDIDhwc/jJT0z3YJEwquV5opgUgmr2G2mdlvW37kldNSToPmpUJw79a23Cz2Phy6VtutP8qJoGrwY1+Mj6nN8htWYnAUi1NdvTPgU+rtkvhYvqPlFYbSWDs++akHFyq9g6Y+b29Mnia8wBJTvHU8PxY2WIdKOTPRqa/TxbaxamYXPTHmvQedh8PRWRAfZKzCvXji6WcURkBWikjE9onu1QF0g3n2UCM1NV4o++aao0/sEJpDH1T/gT/aT1+cFHy+fY+8Ob3+j8bS3LdL2h/BO4pNl8kq53IcWh9rfdpT3i+FBNdW6rCsxVS+xVuk1QJG++PH0l/RCgoHv4emeBLbw1c23ut7phuB4qP+G+kEWv/txCrnt3jbQKNvO5p5wrM+Fj+KyUsq1dRFlGuOwBfiwpcfmp7mwkEktBwq/HC9JVWK3E956KlXCatB0JqEXu+Cwyu4cFrCShBO4EvNg0fCvXZ+TWo0UzCkNMzUr1KLPzZEjN2EVoNMHvb25NXltRgNDCVr17zsuVjRvNcvV8iVOzhR3H0FpETsJr7fj5hQfS7z8+ZVD9egZ1OACYdul7H8zezPnywwx9+IP9f5mM3w=
  - secure: INN0UoNLch5R3Phc4Y5jnVYCBLO6zAr/oC2+rR50VR098+HoHvNvloYJCM4t2yHzC/OOyyV+ej+ydV/JA2drK8HG5uXuKDnv8TSdhWZGAEEKGXyKWKvpNpd99HIYzL+Z49h6XKBEVqgxsd4TsnnS/FLYC4wYKeTBGssVhcIFanxTomRXwLZff1+HrdiEGDSYyG9cNgnRvMMQ/Gb8/9kUbPTNpBwPlY7RUOrevBoQAJESq3+gmYQRiTIPE5iVYTV/Z4KTJxXkZLgSmYFSDBN7X+eLMusTDmYCQUYOuLTzWsn+jvnWw2AI62XeeEl5jVn1ZdO4zPWk3oQEG6GA7cRyzlar2hvGin4qFr4RRSWmgv7h6j028zhjnhpEv878jm0sv4dLYVTJlkumeutxlUwZiiQwmPQzLJBRsoCbmy4SMHhsP304sgwuasQuSU+cXDWtRyKltolBe0DKCcWvInvwE+aRCi8tB93Qt1pcbQMuWIh9BTPC/EmXtkLQKKCvKNV3D0LTT4ogOawhIurjeuom33ouvt9hPj4E+gKSuDvXgXTFX0zWD+0uvhJKWDaqchWe7bosOh3cPZv2+v7tIiEJvS5xbbJzR0tLDIa8TAamfHchPJ9Z2D+Jd5F+9xZkmy7oGVb7EFDIlFfLFG4KxwLjur0AgXN8yPNsaA7wL+kWb24=
  - secure: FSYXdxEfX/staI3mEiXkmwjrJfakRmDpqBK4C14SzDrO3xqhxnF5kgWq6O8ZcDioR0ueEjoloF11A5+HG6wEqSTZcXCubqnrq35gf1P/8MMjKhICZBaYf5LfkOFJMsKM9xWBm1FEg91eCqix3tg6k9nFDB7vrC5WMmVRSlDvzYkca36TnhNXkdsM1wazfVmtt//x/s807Gdy+3fO7peTVe27SyzkiKRUjLJfgnEU7/OX58ebrWvikYLBT5cRxuJaq87s46uI5lHKSVmYdDxnMzZJOlz0E1485ZWsLEOiz60C4reIYET2iXTqKzWjSBMGMnIptPGJBXficLWhPPCw2qwnysz3jwmiXf0PIl0Zi2rdO7nYl7zzSj9uWtoT+5i6GptyiqJy38D9J29dwL1eHMFqZqFETnA8Psiqs5K6c/MxiHoMieV2NebwhZ/WccfMz89S5e6G1ny314Q+h3jvQZaNxDZsTzrWpJ0LuMcdjrVKiWwifjEBcZUPo+LtfZrNoyUY+Dhs24G+qOqZeNgpfuzFtVpGV6h3ZQX5MMILHZ4Wu71Jo+DS1pjyhmSFpXN5ckgNNWXMHq05/5HcjZ4ya6u7vdFnlYoDjC0KRxyD5WUbxChbKMeoaHXuZYP5a1LimUS0Qche8KP8Y2KjQSrWZQtqNmrfTvHuZTABp+gHiEE=
  - secure: dkZSPoiBPMGoUxTY//sErXssBKAYd0MbSjyVyo0d59sGCPiKxDcaxjS0pCNw8BjmSPOVgePDUsZvIXAKLyBmWRT0kBH9NCCVjvu1aAnSh3vpUJroCPM9RnhuFeFzYKq1gGhHE89I9RPe7T7MbuR/eMvGC734xlubkZPbuQKPAILoAFizU+7AKfuA9cz32HHUGgsbU6UL/BRPt6LaEFQ7kTZArpzIpRN+tGOHHGpIToyf/aAcYO08oV0WknjyjqoCZMRZR4P50ITWpnX4QqSI4s6Z2t70tHbDDw+c5mChEPVQDtdY38RkLClcH+Ru7zTZ0ZSrFTUYA8htlB0fTIdy3VZfjXJi6KRa4K8h9QH0JTIaZ2VLLghVDYlV5ANSSlMto+54CVw4kYPyPhO1qbdp5vzKx/0F2fO/lc1LuGv3KOcq+/UfFH8v13bE4ZrLikZiw7xYYNKOE2gUcYkEklBpBzpnTQO+c8zWsghMZcCUhY9L+8KTmTUolMEmFlvcCu19dFQVviobtcCN1dSd3q/OTIqNDmbv4tZBGtQ5zGksdEeM/W3hjiyc6E98NkWTga6GnuW+1GPpSDCaxIm9nZVKCNfV1e8dzSZkJhZaG0Le27L626AlkSu9jqPu+JtwmG+kBpsmnaOUnCSLrmSC5DWsdf05vW/9PHGWZCfqGRs5smY=
  - secure: e95yGhmgEVYDnH3Wy3XxTpBmcKMIp0Nt2cfYlZG0PuWl0SJ1/1jxRhMT93OdrSrCmBq/pX0YkPrvBC9A4PWN2o2mqTtm1DBpySx9Ew2yIYy3NU0DJu3ELBHEkzVe68JZLKDSYc9OPR/B44z5C+hPKKw9Z1qe3EHxkYxznZyZUrdNavK2oauf7Q7AQp2+9bgk10VsBiEpK9JjKNk3+S4x4HbCpCBGI0YIoL4nWDqdsGfdC9Q9WBySY0RRqeAWzauqlKobWEbxSaG7zPievvuGTVoMXaRotiDC6LTjoa940OdHa8QUwbbkrxFDcgA8xD38Sb0M100Qi+53QHI/HRoz5zTGheB6Om3BYat/j299bmVEa0LgaTpl73qAo/Z/HdKnFfHUcycdffXuj/zkLI96638lUgbRV7N5vhIXf1Vl3xiSfeBjkbIYNuELkHI5VdteQrasx6AuEFMhHSWgSrwpbDGrpWij3EOkDRoIi0JP96v8gbZZL3o32/C/625xcWjyuEn+29ygKsPnI756cWwXY+JtcI0T2hVLJFTJr49C3y6/1z0mUh2B167+7l7VluQ43ZshzNhViOiKtD2ZWqyXHGI2ySmMTIKOYxafA/d+k3HprgfX+/gbSPuMXuJIBGvzNyWZZs7LOtAZX6pemYjs1ZVehDrQX2jSIN7QyvX2nNA=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=18.191.95.13
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
