language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - biss_dimov@hotmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: PHfW9kqTgRMAWBhvMkSAO2dCvKT5645teyngT/ephWOC+vntBft1riw2QFL6aUxIMpsr+0/aq+1r8l1jeiPgalABM0oA93HNNKK1dAZZ8r7hnJoCLw7hTIl6ygJgGVjFQ0NXLLdJnWhWAlfY5Zs/neCYQHmpUmpCgsrSpesZQPr8YYodWaauebs/8q821Qu1aVtqPTSgsvhzr5pBFymY4v8fbhyhhkD+XvRZrgJIBMLpim0CwHE+uTHSRjS5diom18dqlP9mECZkJcclqP/rS6uTHqj4HMhRxVyfixVMAn2/Ccb3MdhLn5iMWeDF8lzrVanUDmFhrf3B/pfctUrBqGVWZcmZQU7F7TJh2BpmBzoQrS8lmjHSYzntvoh4RQ+lmQjdldAzMKE3dxrrrA2aYptnkAiUZo8aWY/70rYE/PLX1wO+bAKBEUgwGkNcihlQ7UoPu2QYNvLIEK6ue8EyEN71NHzRn/ORK01WssIWJDasYCf96njUKrPow2DUVDGvCMIn5bOYkS/A/3NlEVuQ0X2a911ehJz9/W66JoYTXEwdONj+kJVcziQrmUO9OgZK1bJ43s+waEv4X+tocQRTvRy3ZfE6LiocT/ho4uIUKd6ltYXRWv6f/qTS8wLUXU4cqVc5znTVeUxTxkhvDLWMG+8pi7iUL8IuCrxfZdfgaKM=
  - secure: R03UDEMyqZ0LLHRg1nNMPMgKvN3ezESkP2+45JMdLjWMuFTLOJJ7T+73D6+GNUH0JvEpNwsTNJexNz+i3MVAIHS7eG+fjvVxoRHVxyWdrWVyITaW4riZ1HaWvsiT0nDCa0h0KrTXADayYm7Ho1/vx2PR2ZcT96VbffnroDJYTqR5MjCJjbJ33xXng6wF4huON2MAK1qZTWqA3Um7eGZe7WR0V0ppZWie4YlDD4N3vEl2axr5uMoyGpL8Z4pcU0kUQVPdmaZyzDGctupegrGqQdGk8HH49Q9p4I+M39Yxzbc3KvmW3WKWhxmICEbljQU5hnQuyL21skotNBbm3HF25D6LenT8O7cbgKnKP1S74lzN19Tcn8d2BS0Cffg+trmS2npB9lXg5cVONdQbC3t/n5HJFECBTLdpuFCi/+OEVkXuooW8zWMunXoDXodUKjcZ69M5+Vo/R3eZC5TB6+4snqysS8e6V01M99I2QcxQkNBAYgPC1pWj1BtqVQ69UIan9Y4nViUZBYvmk9uuOVs2IjOspiPMaq7947VKvK6RlCyZww2z3HSotLPzk0rUV8eeLMdi0KjrRLWzf7qYtCMKe5Hl4pc9u0fqJxM64kXR6xXm1k8yTZCBRO2xM8TixIUa3SsXrbtbW7MJa1N09zhktXv17M6phsXUE3YBBsZESSU=
  - secure: VTX16FGkVFF35TnyWyC3NkNIUDMgierldE9kC6L8ep6Q28Gfp/cZ542D6asQ57XN7MW/IyEU7r0mHTfcWcuRx8re3mnAhn+GbGgwXz91lJjEh4VtRygbmfPssH1K/NV8/rWOo4v900Q8S+qKfSyZCc8e4wCn5kKCTNf92yoa9FaA3joJpiK8YBsEEFJ1TM4/zsqMk0OSy55573filQu2UZlJ3br5aKTwCF7Urdoo0h1eoo8DhgF8yOwJpVkRxVJjF8F7ZGlAvIxZHdf7sYC8HjtGpYK/BxCMKz4/LwvQEDtsCfsRoiyXTDEugXoJI64//v8AhcNej5kbRgPbVoT04U2CLXESK5bNjbtPD/Z63MPAjR16QBrXjLJUTLN8rbkC8EJrie5ncVCgCZ9qWzNYJY2qVhxYXKzF+GimlhYx7mXIk4oRRD4Ojx3sixmWaPBDBper5SXKdQpM2ZTXeYBtzgUui/Q41hRBF17fcqTC51aGEwBJxb8hJZcoDEQ/6zegFoijlMsIrGpHPQhDIviuQ45bR91WM9ryVR4NJEYfBXNkyVAYCWoiTsHlxMxxjPFif+XdtFN+vtmji+MYbh2ZcAvLJXL3ko2J/taxzsSz3v+PnXpTdVQvA4E8UGeb2PFluW2HnqlXjFxBwN9ivwu+3f4GNBnhjidX/lXDR9JrYII=
  - secure: UfzDUmxFgAwDV7TYPVEz3N9mR31Xv8RYx9tj9fjBXyTWtWH2uFhWAu5eesPSuSG/mNavSmvdd3zqolebMYOEfj/A/VVnrrJ9oMLjJtx6hUgzV07SUL26puUAuEEg4pNXXxAesghcvMT7+AbiQ8y5whcB7CEbMin4IbwHt4PvzxqQFfax2Q9XG+E7hw0EFeUtYxtH6hBkWCZS80ekoilBMne/laGrCyEimqK+Wnp0w7ZQ9UrW+sMCAsPquYAlktWW1tmTVTY19rm1AqZCS0T6r3lXznBRuibhfGNat1F9u87yp90alYfrpduTNSPPboDIXvVt6fHwGhYsNcXvvIsRmg1GlhJn88WkiMgMdL+Q9JqpogtjojAwFJAiCr8VGAbuD/xq0qXWMUfjbpjxnLTeuQWCzuL4DZUJSSGwBBhB0JP9Y2g1tN5v65lF56ELXwPQVcbg/GV0mq2LpEaLXFoG/i2P+0sBKal3RVNeXWCUUTrD0VAC3TkN+OT9lCvuo0IR/wM01GkWLUAWIKM8i2LZ3n0O52jUGW8ePjABzQlRUrUPpg4Sv2dqt0Q6wzrwAK2nzw31EGUZ+My3AkfhN0r+wSoAvK/7uui12/+QbzDwiwIhxb4zxGy6sWzRpAbENQZLS/mretWZJ5x6hZ3QfEVabo0FwEv/oUOc3vSf6ecyomo=
  - secure: SL1zVNn+3l0KapXQyf8+Fw4OZO5MmOytddScGY8+gcJWdjXc5NNh2CaFF3/03DgyV48JA0iILNwVzJzfV2y1tHmhVaamE8ajjHJkomd1Xy/tXEk2hIu+PSHja80rUR4uvq2gwLu2U0bn6LUVBdcrD8fgKxvyXQOfhKepRPF4ochJH/ts7iFWsLunlRxPMv76kKgGwrTvtJyWk1UCdIpgefzLT8SFS3rl47Yv+l8IY/9nKKrewnKuY8yYEsNxR8fzTdreu8Irl2iT337vvWmno7ufSL2tfr9hPzPitVghRD94pri5jfPgyURaxmdApBsfJUMDHFpG+CX3ZUSEUBB1kRjnnxEKIHKkiCZwmJEbr6JMYP9eBLdGhMpb+k4drNMZvXzwqQwVtthh5xLBG418hPB9hLKN0hFRtXIgVhBVqd7df9+ux+S8Dlvip/SGIVE4FwnasHBKDov+VQMeQIVeCNWx/071MaAXx3j0znQfnZ724MYjGSxgfWpcnPZ04Te9Kk/N57a8nCXsgulVthxudqEaUT42Essa5VY6QmQ6gGgcT7nOzkCzvwKqex6cqzv5b9dBZmo7p7xW3ooqofy7LYkViCve5XJ2gmLhj7r6NJ5ypFGiY89uwiAblIDVW+XzDo0kZ12b219ZgCg3ya8XzS8cbCWCoVs8ZtcBXP7pBas=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=18.191.95.13
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
